version: '3'
services:
  web:
    build: web/
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USERNAME=dbuser
      - MARIADB_PASSWORD=dbuser
      - MARIADB_DATABASE=testdb
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/backup:/var/lib/backup
      - ./mysql-init-files:/docker-entrypoint-initdb.d
  scraper:
    build: scraper/
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  ai:
    build: ai/
    ports:
      - "3000:3000"
    
