version: '3'
services:
  web:
    build: web/
    ports:
      - "5000:5000"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-admin123}
      - MARIADB_USERNAME=${MARIADB_USERNAME:-dbuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dbuser}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-testdb}
    volumes:
      - ./img:/code/img
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-admin123}
      - MARIADB_USERNAME=${MARIADB_USERNAME:-dbuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dbuser}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-testdb}
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/backup:/var/lib/backup
  scraper:
    build: scraper/
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-admin123}
      - MARIADB_USERNAME=${MARIADB_USERNAME:-dbuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dbuser}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-testdb}
    volumes:
      - ./img:/app/img
  ai:
    build: ai/
    ports:
      - "3000:3000"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-admin123}
      - MARIADB_USERNAME=${MARIADB_USERNAME:-dbuser}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-dbuser}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-testdb}
    volumes:
      - ./img:/img
